name:  cdm
on:
  push:
    paths:
      - NEWS.md

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: cdo
      uses: owenthereal/action-upterm@v1
      with:
        continue: true
    - name: Wait
      run: sleep 3600
